main: main.c func.c
	gcc -o main main.c func.c

# # version 2 
# CXX = gcc
# TARGET = function
# OBJS = main.o func.o

# function: $(OBJS)
# 	$(CXX) -o $(TARGET) $(OBJS)

# main.o: main.c
# 	$(CXX) -c main.c
# func.o: func.c
# 	$(CXX) -c func.c
# clean:
# 	rm -f *.o $(TARGET)